remote_theme: pmarsceill/just-the-docs
color_scheme: nil
url: "https://symphonyosf.github.io"

# Aux links for the upper right navigation
aux_links:
 "API Source Code":
  - "//github.com/SymphonyOSF/oss-sym20"

search_enabled: true